In [ ]:
import numpy as np
import pandas as pd
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/python-Saylani/customer.csv')

In [ ]:
df.sample(5)

age  gender   review education purchased
18   19    Male     Good    School        No
37   94    Male  Average        PG       Yes
41   23    Male     Good        PG       Yes
24   16  Female  Average        PG       Yes
13   57  Female  Average    School        No

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [ ]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [ ]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(['purchased'],axis=1)
y=df['purchased']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

review education
38     Good    School
16     Poor        UG
27     Poor        PG
33     Good        PG
40     Good    School
29  Average        UG
10     Good        UG
5   Average    School
28     Poor    School
4   Average        UG
31     Poor    School
13  Average    School
36     Good        UG
11     Good        UG
21  Average        PG
48     Good        UG
7      Poor    School
49     Good        UG
14     Poor        PG
47     Good        PG
44  Average        UG
22     Poor        PG
3      Good        PG
41     Good        PG
34  Average    School
12     Poor    School
18     Good    School
35     Poor    School
45     Poor        PG
23     Good    School
42     Good        PG
30  Average        UG
17     Poor        UG
2      Good        PG
37  Average        PG
6      Good    School
32  Average        UG
26     Poor        PG
15     Poor        UG
24  Average        PG

In [ ]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [ ]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
x_train = oe.transform(x_train)

In [ ]:
x_train

array([[2., 0.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 2.]])

In [ ]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [ ]:
x_train

array([[2., 0.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [2., 1.],
       [2., 1.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 2.]])

In [ ]:
y_train

38     No
16    Yes
27     No
33    Yes
40     No
29    Yes
10    Yes
5     Yes
28     No
4      No
31    Yes
13     No
36    Yes
11    Yes
21     No
48    Yes
7     Yes
49     No
14    Yes
47    Yes
44     No
22    Yes
3      No
41    Yes
34     No
12     No
18     No
35    Yes
45    Yes
23     No
42    Yes
30     No
17    Yes
2      No
37    Yes
6      No
32    Yes
26     No
15     No
24    Yes
Name: purchased, dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(y_train)

LabelEncoder()

In [ ]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_test

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1])